version: '3.9'

services:

  ##
  # Nginx
  ##
  vvveb-develop:
    restart: always
    image: nginx:alpine

    networks:
      - wpdevnet

    ports:
      - 80:80

    volumes:
      - ./tools/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/vvveb

    depends_on:
      - phpfpm

  ##
  # PHP
  ##
  phpfpm:
    restart: always
    image: bitnami/php-fpm:7.4

    networks:
      - wpdevnet
    
    ports:
      - "9000"
    
    expose:
      - "9000"

    volumes:
      - ./tools/php/php.ini:/opt/bitnami/php/etc/conf.d/custom.ini
      - ./:/var/www/vvveb

    depends_on:
      - mysql

  ##
  # MySQL
  ##
  mysql:
    image: mysql:latest

    environment:
      MYSQL_ROOT_PASSWORD: password
    
    networks:
      - wpdevnet
    
    ports:
      - "3306"

    expose:
      - "3306"

    volumes:
      - ./tools/mysql/mysql-init.sql:/docker-entrypoint-initdb.d/mysql-init.sql
      - mysql:/var/lib/mysql

    # For compatibility with PHP versions that don't support the caching_sha2_password auth plugin used in MySQL 8.0.
    command: --default-authentication-plugin=mysql_native_password

volumes:
  # So that sites aren't wiped every time containers are restarted, MySQL uses a persistent volume.
  mysql: {}
networks:
  # Creating our own network allows us to connect between containers using their service name.
  wpdevnet:
    driver: bridge
